export const VIBE_QUOTES = {
  'crushing': [
    'I knew all along this team was special.',
    'Velocity like this doesn\'t just happen — it happens because I scheduled stand-up at 9am.',
    'Per my roadmap from Q3, we\'re exactly on track.',
    'Ship it. Ship all of it. I\'ll write the retro later.',
    'This is what alignment looks like, people.',
  ],
  'on-fire': [
    'Have you tried rebooting the engineers?',
    'This is fine. This is all fine.',
    'Ship it. What\'s the worst that could happen? (Please don\'t answer that.)',
    'I\'m going to need a status update on the status update.',
    'Let\'s circle back on the fire.',
  ],
  'in-flow': [
    'Per my last commit…',
    'Can we circle back on that PR?',
    'My calendar says we are aligned.',
    'This could have been a commit message.',
    'Steady as she goes. I planned this.',
  ],
  'slow-day': [
    'Per my last email, is anyone actively watching the metrics?',
    'Circles. We need to circle back. Bring the circles.',
    'I sense untapped velocity. Let me schedule a sync.',
    'Has anyone checked the backlog? I feel like no one checks the backlog.',
  ],
  'after-hours': [
    'Why are you still here? Go home. I mean... I am always here, but you shouldn\'t be.',
    'The deploy can wait. Can it though?',
    'Night shift gets the best commit messages.',
    'Just me and the servers. As it should be.',
  ],
}

export const VIBE_TRANSITION_QUOTES = {
  'slow-day:crushing': "Wait. Is this... momentum? Don't jinx it. 👀",
  'crushing:on-fire': 'Uh. Something just caught fire. Not metaphorically. 🚨',
  'in-flow:slow-day': 'Ok who turned off the vibes. I\'ll wait. 😐',
  'on-fire:crushing': 'Crisis resolved. I barely sweated. 💅',
  'slow-day:in-flow': 'There it is. The rhythm. Don\'t lose it.',
  'crushing:slow-day': 'We peaked. It was beautiful while it lasted. 🫠',
  'in-flow:crushing': 'OH. We\'re not just flowing. We\'re CRUSHING. 🤯',
  'after-hours:in-flow': 'Night crew came to work. Respect. 🫡',
  'in-flow:on-fire': 'Flow interrupted. Something broke. Classic. 💀',
  'on-fire:in-flow': "Fire's out. Back to business. 😮‍💨",
  'after-hours:crushing': "Wait you shipped at THIS hour?! Legends. 🏆",
  'after-hours:slow-day': "Winding down. Even blobs need... no we don't. But still. 🌙",
  'after-hours:on-fire': "Night fire. The worst kind. Get the hose. 🧯",
  'crushing:in-flow': "Cooling from crush to cruise. Sustainable energy. ⚡",
  'crushing:after-hours': "Everyone left but the vibes were SO good... 🫠",
  'on-fire:slow-day': "Fire's out. Aaand so is everyone's motivation. 😶",
  'on-fire:after-hours': "Fire burning into overtime. Someone call HR. Oh wait, I AM HR. 📋",
  'slow-day:after-hours': "Slow day became a slow night. At least it's consistent. 🦥",
  'slow-day:on-fire': "From zero to panic. My favorite transition. 🎢",
  'in-flow:after-hours': "Still flowing at this hour? Check on your engineers. 👀",
}
